### ISSUE TITLE
The distance threshold (_lambda=1.6) for edges in MD17

### ISSUE THREAD

**Issue by chocolates** [hanjq17/GMN#2]
Hi,
For the MD17 dataset, if I understand it correctly, you use the ``_lambda`` (https://github.com/hanjq17/GMN/blob/main/spatial_graph/md17/dataset.py, line 85 ) as the distance threshold to determine which nodes are connected by edges. According to the paper, this threshold should enable connecting 2-hop neighbors for every atom. 
May I ask how to determine this threshold, e.g., how do you know to set ``_lambda=1.6`` rather than ``1.5``, ``1.7`` to guarantee connecting 2-hop neighbors?  is there any reference for this value? 
Thank you in advance!

**Comment by hanjq17** [comment]
Hi,

It was just out of empirical reason. The bond connection for these MD17 molecules happens to be distinguishable by the cutoff 1.6. I double checked the bond connection determined by cutoff=1.6 with that produced by rdkit, and it happened to be the same. However, cutoff like 1.5 or 1.7 will not work (I remember the exact threshold was really close to 1.6, otherwise there will be mis-connection). 
Overall, the threshold only work for MD17 data, and if you would like to work on other data, it would be better to apply packages like rdkit to generate high-fidelity bond connection info.

Hope these explanations well answer your question.

Best,
Jiaqi

**Comment by chocolates** [comment]
Ok, thanks for clarifying it.
